import {lazy,Suspense,useEffect,useMemo,useRef,useState} from 'react'
import {ArrowLeft,ArrowRight,Bookmark,Check,ChevronDown,ChevronUp,Compass,Download,ExternalLink,Heart,Home,LoaderCircle,LockKeyhole,Map,MapPin,Plus,RotateCcw,Settings2,ShieldCheck,SlidersHorizontal,Sparkles,Trash2,UnlockKeyhole,X} from 'lucide-react'
import {api} from './domain'
import type {Brief,Candidate,Fact,Health,Itinerary,Plan,Run} from './domain'
import {useSession} from './session'
import {exampleDestinations,exampleTrip} from './examples'
const TripMap=lazy(()=>import('./TripMap').then(m=>({default:m.TripMap})))
import './App.css'
import './editorial.css'
type Route='home'|'brief'|'results'|'trip'|'saved'|'settings'
const go=(route:Route)=>{location.hash='#/'+route;window.scrollTo({top:0})}
const hashRoute=():Route=>['brief','results','trip','saved','settings'].includes(location.hash.slice(2).split('?')[0])?location.hash.slice(2).split('?')[0] as Route:'home'
const photos=['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=80','https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=900&q=80']
const topics=['自然风景','在地美食','城市漫游','人文历史','海边散步','亲子体验']
function Header({title,back='home',children}:{title:string;back?:Route;children?:React.ReactNode}){return <header className="page-header"><button className="icon-button" onClick={()=>go(back)} aria-label="返回"><ArrowLeft size={20}/></button><strong>{title}</strong><div>{children}</div></header>}
function Pill({example=false}:{example?:boolean}){return <span className={'pill '+(example?'example':'')}><span/>{example?'示例行程':'真实查询'}</span>}
function App(){
 const [route,setRoute]=useState<Route>(hashRoute),[health,setHealth]=useState<Health|null>(null),[run,setRun]=useState<Run|null>(null),[error,setError]=useState(''),[info,setInfo]=useState(false),[busy,setBusy]=useState(false),[detail,setDetail]=useState<Fact|null>(null)
 const {brief,trips,selectedId,runId,setRun:setRunId,saveTrip,saveError,retry}=useSession();const trip=trips.find(t=>t.id===selectedId)||null
 useEffect(()=>{const h=()=>setRoute(hashRoute());addEventListener('hashchange',h);api<Health>('/health').then(setHealth).catch(()=>setError('服务暂时不可用，请检查启动状态后重试。'));api<{trips:Itinerary[]}>('/trips').then(r=>{if(r.trips.length)useSession.getState().mergeTrips(r.trips)}).catch(()=>{});return()=>removeEventListener('hashchange',h)},[])
 useEffect(()=>{if(!runId)return;let disposed=false;const load=async()=>{try{const result=await api<Run>('/planning-runs/'+runId);if(!disposed)setRun(result)}catch(e){if(!disposed){setError((e as Error).message);setRunId(null)}}};void load();const timer=setInterval(()=>void load(),1800);return()=>{disposed=true;clearInterval(timer)}},[runId,setRunId])
 const start=async(kind:'discover'|'plan'|'adjust',data:Brief,request='',scopeDays:number[]=[]) =>{setError('');setBusy(true);try{const result=await api<Run>('/planning-runs',{kind,brief:data,request,scopeDays,idempotencyKey:crypto.randomUUID(),...(kind==='adjust'&&trip?{tripId:trip.id,baseRevision:trip.revision}:{})});setRun(result);setRunId(result.id);go('results')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const save=async(plan:Plan,lockedIds=trip?.lockedIds||[])=>{if(!trip)return;setError('');try{if(trip.dataMode==='example'){saveTrip({...trip,plan,lockedIds,revision:trip.revision+1,updatedAt:new Date().toISOString()});return}const result=await api<{trip:Itinerary}>('/trips/'+trip.id,{baseRevision:trip.revision,plan,lockedIds});saveTrip(result.trip)}catch(e){setError((e as Error).message)}}
 const viewExample=(id:string)=>{saveTrip(exampleTrip(id,brief.days===5?5:3));go('trip')}
 const active=run&&['queued','running'].includes(run.status)
 return <div className="workspace"><div className="app-frame"><main>
  {saveError&&<div className="notice danger" role="alert">{saveError}<button onClick={retry}>重试保存</button></div>}
  {error&&<div className="notice danger" role="alert">{error}<button className="icon-button" onClick={()=>setError('')} aria-label="关闭错误"><X size={16}/></button></div>}
  {active&&route!=='results'&&<button className="run-banner" onClick={()=>go('results')}><LoaderCircle className="spin" size={16}/>规划正在进行 · 查看进度<ArrowRight size={15}/></button>}
  {route==='home'&&<HomePage health={health} trip={trip} openInfo={()=>setInfo(true)} viewExample={viewExample}/>}
  {route==='brief'&&<BriefPage health={health} busy={busy||Boolean(active)} start={start}/>}
  {route==='results'&&<ResultsPage run={run} busy={busy} start={start} cancel={async()=>{if(run){const r=await api<Run>('/planning-runs/'+run.id+'/cancel',{});setRun(r)}}} resume={async answer=>{if(run){setBusy(true);try{setRun(await api<Run>('/planning-runs/'+run.id+'/resume',{answer}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}} apply={async()=>{if(!run)return;setBusy(true);try{const r=await api<{trip:Itinerary}>('/planning-runs/'+run.id+'/apply',{baseRevision:run.baseRevision,confirmationId:run.confirmationId});saveTrip(r.trip);setRunId(null);setRun(null);go('trip')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}/>}
  {route==='trip'&&<TripPage trip={trip} health={health} busy={busy||Boolean(active)} save={save} key={trip?.id} detail={setDetail} adjust={(text,days)=>trip?start('adjust',trip.brief,text,days):Promise.resolve()} undo={async()=>{if(!trip)return;try{const r=await api<{trip:Itinerary}>('/trips/'+trip.id+'/undo',{baseRevision:trip.revision});saveTrip(r.trip)}catch(e){setError((e as Error).message)}}}/>}
  {route==='saved'&&<SavedPage/>}
  {route==='settings'&&<SettingsPage health={health} refresh={async()=>setHealth(await api<Health>('/health'))} onError={setError} cleared={()=>{setRun(null);setError('')}}/>}
 </main><nav className="bottom-nav" aria-label="主导航">{[{r:'home',icon:Home,label:'探索'},{r:'saved',icon:Map,label:'我的行程'},{r:'settings',icon:SlidersHorizontal,label:'设置'}].map(({r,icon:Icon,label})=><button key={r} onClick={()=>go(r as Route)} aria-current={route===r?'page':undefined} className={route===r?'active':''}><Icon size={21}/><span>{label}</span></button>)}</nav></div>
 {info&&<Modal title="从想法到行程" close={()=>setInfo(false)}><p>先找到适合的目的地，再规划每一天。你可以手动编辑，也可以让 AI 提出调整；确认前，原行程保持原样。</p><p>真实查询需要配置模型与地点服务。示例内容会单独标注，不代表实时查询结果。</p><button className="primary-button" onClick={()=>{setInfo(false);go('settings')}}>查看服务状态</button></Modal>}
 {detail&&<Modal title={detail.name} close={()=>setDetail(null)}><Pill example={!detail.verified}/><p className="muted">{detail.category} · {detail.address}</p><div className="facts-grid"><div><small>开放时间</small><strong>{detail.openingHours||'待核实'}</strong></div><div><small>票价与预约</small><strong>{detail.ticketPrice||'待核实'}</strong></div></div><p className="muted">{detail.verified?'地点来自资料查询。开放时间与预约请以官方当日信息为准。':'这是交互示例，地点事实尚未实时核查。'}</p><a href={detail.sourceUrl} target="_blank" rel="noreferrer">查看地点来源 <ExternalLink size={14}/></a><p className="footnote">资料时间：{detail.retrievedAt}</p></Modal>}
 </div>
}
function HomePage({health,trip,openInfo,viewExample}:{health:Health|null;trip:Itinerary|null;openInfo:()=>void;viewExample:(id:string)=>void}){
 const setBrief=useSession(s=>s.setBrief),brief=useSession(s=>s.brief)
 const [idea,setIdea]=useState(''),[filter,setFilter]=useState('全部'),[favorites,setFavorites]=useState<string[]>(()=>{try{const x=JSON.parse(localStorage.getItem('travel-inspiration-favorites')||'[]');return Array.isArray(x)?x.filter((v):v is string=>typeof v==='string'):[]}catch{return []}})
 const begin=(known:boolean)=>{setBrief({...brief,destination:known?brief.destination:'',request:idea||brief.request});location.hash='#/brief?mode='+(known?'known':'discover');window.scrollTo({top:0})}
 const moods=[{tag:'自然',title:'把时间交给山野',caption:'山间散步 · 慢一点的日常'},{tag:'城市',title:'走进一座城的日常',caption:'街巷漫游 · 在地风味'},{tag:'水岸',title:'在水岸，留一点空白',caption:'临水散步 · 轻松出发'}]
 const toggle=(id:string)=>{const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(next);try{localStorage.setItem('travel-inspiration-favorites',JSON.stringify(next))}catch{/* Favorites remain available for the current page session. */}}
 return <div className="screen home-screen"><header className="home-header"><div className="brand"><Compass size={22}/><b>旅行计划</b><span className="brand-divider"/><small>让出发更简单</small></div><button className="avatar-button" onClick={openInfo} aria-label="产品说明"><span>旅</span></button></header>
 <section className="editorial-hero"><img src={photos[2]} alt="湖岸与远山的旅行氛围" fetchPriority="high"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">THE ART OF GETTING AWAY</p><h1>世界很大，<br/>找到你的下一站。</h1><p>从一点心动开始，<br/>把旅程安排成你喜欢的样子。</p></div><span className="photo-caption">旅行氛围图</span></section>
 <section className="ask-card"><div className="ask-title"><Sparkles size={18}/><b>这一次，想怎么出发？</b></div><textarea aria-label="旅行想法" placeholder="三天假期，想看海、吃点好的，走得慢一点……" value={idea} onChange={e=>setIdea(e.target.value)} maxLength={2000}/><div className="ask-bottom"><span>{health?.ready?'根据你的想法查询并规划':'先写下想法，或体验示例'}</span><button onClick={()=>begin(false)} aria-label="开始探索">开始探索<ArrowRight size={16}/></button></div></section>
 <div className="quick-start"><button onClick={()=>begin(false)}><Sparkles size={17}/><span><b>还没想好去哪</b><small>一起找个喜欢的地方</small></span><ArrowRight size={16}/></button><button onClick={()=>begin(true)}><MapPin size={17}/><span><b>已经有目的地</b><small>开始安排每一天</small></span><ArrowRight size={16}/></button></div>

 <section className="inspiration"><div className="section-title"><div><p className="eyebrow">PLACES & POSSIBILITIES</p><h2>有些地方，值得出发</h2></div><span className="subtle-label">灵感示例</span></div><div className="inspiration-filters" aria-label="筛选旅行灵感">{['全部','自然','城市','水岸','已收藏'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='已收藏'&&<Bookmark size={12}/>} {f}</button>)}</div><div className="inspiration-grid">{exampleDestinations.map((d,i)=>({d,i})).filter(({d,i})=>filter==='全部'||filter===moods[i].tag||(filter==='已收藏'&&favorites.includes(d.id))).map(({d,i})=><article className="discovery-card" key={d.id}><div className="discovery-photo"><button className="discovery-open" onClick={()=>viewExample(d.id)} aria-label={'查看'+d.name+'示例行程'}><img src={photos[i]} alt={moods[i].title+'，旅行氛围图'} loading="lazy"/><span className="image-shade"/><span className="discovery-tag">{moods[i].tag} · 氛围图</span></button><button className={'favorite-button '+(favorites.includes(d.id)?'selected':'')} onClick={()=>toggle(d.id)} aria-label={(favorites.includes(d.id)?'取消收藏':'收藏')+d.name} aria-pressed={favorites.includes(d.id)}><Heart size={16} fill={favorites.includes(d.id)?'currentColor':'none'}/></button></div><button className="discovery-copy" onClick={()=>viewExample(d.id)}><small>{moods[i].caption}</small><h3>{moods[i].title}</h3><span>{d.name} · 3 / 5 天示例<ArrowRight size={14}/></span></button></article>)}</div>{filter==='已收藏'&&!favorites.length&&<div className="empty-inline">收藏一份心动，留给下一次出发。</div>}<p className="footnote">图片展示旅行氛围，示例地点与安排未经过实时查询。</p></section>
 {trip&&<button className="continue-card" onClick={()=>go('trip')}><div className="continue-icon"><Map size={23}/></div><div><small>继续你的旅程</small><b>{trip.plan.destination} · {trip.brief.days} 天</b><span>{trip.dataMode==='example'?'示例行程':'已保存'} · 按自己的节奏调整</span></div><ArrowRight size={18}/></button>}
 <section className="travel-promise"><p className="eyebrow">A PLAN, WITH ROOM TO WANDER</p><h2>有计划，也有余地。</h2><p>每天去哪里、怎么走，一目了然。<br/>想换一种节奏，随时调整。</p><button onClick={()=>begin(true)}>开始我的旅行计划<ArrowRight size={16}/></button></section></div>
}
function BriefPage({health,busy,start}:{health:Health|null;busy:boolean;start:(kind:'discover'|'plan'|'adjust',b:Brief)=>Promise<void>}){
 const {brief,setBrief}=useSession();const [known,setKnown]=useState(location.hash.includes('mode=known')||Boolean(brief.destination)),[validation,setValidation]=useState('')
 const update=(p:Partial<Brief>)=>setBrief({...brief,...p});const submit=(e:React.FormEvent)=>{e.preventDefault();if(known&&!brief.destination.trim()){setValidation('请填写想去的目的地');return}if(!known&&!brief.origin.trim()){setValidation('请填写出发地，方便比较目的地');return}setValidation('');void start(known?'plan':'discover',{...brief,destination:known?brief.destination.trim():''})}
 return <div className="screen"><Header title="这次，想怎么旅行？"/><div className="segment"><button className={!known?'active':''} onClick={()=>setKnown(false)}>还没决定去哪</button><button className={known?'active':''} onClick={()=>setKnown(true)}>已有目的地</button></div><div className="page-intro"><p className="eyebrow">MAKE IT YOURS</p><h2>{known?'按你的节奏，安排每一天':'先找到适合你的去处'}</h2><p>从必要的条件开始，其余的可以边聊边调整。</p></div>
 <form className="brief-form" onSubmit={submit}>
 <label className="field"><span>从哪里出发 {known?<em>可选</em>:<em>必填</em>}</span><input value={brief.origin} onChange={e=>update({origin:e.target.value})} placeholder="例如：上海" maxLength={80}/></label>
 {known&&<label className="field"><span>想去哪里 <em>必填</em></span><input value={brief.destination} onChange={e=>update({destination:e.target.value})} placeholder="例如：成都" maxLength={80}/></label>}
 <div className="field-row"><label className="field"><span>旅行天数</span><select value={brief.days} onChange={e=>update({days:Number(e.target.value)})}>{Array.from({length:14},(_,i)=><option key={i} value={i+1}>{i+1} 天</option>)}</select></label><label className="field"><span>出发日期 <em>可选</em></span><input type="date" value={brief.startDate} onChange={e=>update({startDate:e.target.value})}/></label></div>
 <label className="field"><span>总预算（人民币）<em>可选</em></span><input type="number" min="1" max="1000000" value={brief.budget??''} onChange={e=>update({budget:e.target.value?Number(e.target.value):null})} placeholder="例如：3000"/><small>作为规划条件；查询不完整时会明确提示费用尚未核实。</small></label>
 <fieldset><legend>更想体验什么 <em>可多选</em></legend><div className="chips">{topics.map(t=><button type="button" key={t} className={brief.interests.includes(t)?'selected':''} onClick={()=>update({interests:brief.interests.includes(t)?brief.interests.filter(x=>x!==t):[...brief.interests,t]})}>{t}</button>)}</div></fieldset>
 <fieldset><legend>旅行节奏</legend><div className="chips">{(['松弛','均衡','充实'] as const).map(p=><button type="button" key={p} className={brief.pace===p?'selected':''} onClick={()=>update({pace:p})}>{p}</button>)}</div></fieldset>
 <label className="field"><span>和谁出发</span><select value={brief.companion} onChange={e=>update({companion:e.target.value})}>{['一个人','和朋友','情侣','亲子'].map(x=><option key={x}>{x}</option>)}</select></label>
 <label className="field"><span>更多想法 <em>可选</em></span><textarea value={brief.request} onChange={e=>update({request:e.target.value})} placeholder="想看海、每天晚一点出门……" maxLength={2000}/></label><label className="field"><span>一定要满足的条件 <em>可选</em></span><textarea value={brief.constraints} onChange={e=>update({constraints:e.target.value})} placeholder="例如：不自驾，周二下午已订博物馆" maxLength={1000}/></label>
 {validation&&<p className="notice danger" role="alert">{validation}</p>}
 {health&&!health.ready&&<div className="notice"><Settings2 size={17}/><span>真实规划服务待配置。现在可以填写并保存条件，或返回首页体验示例。</span><button type="button" onClick={()=>go('settings')}>查看</button></div>}
 <button className="primary-button" type="submit" disabled={busy||!health?.ready}>{busy?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>}{known?'查询并生成行程':'帮我比较目的地'}</button><p className="footnote">提交后将查询外部资料。确认行程前不会覆盖已有计划。</p></form></div>
}
function ResultsPage({run,busy,start,cancel,resume,apply}:{run:Run|null;busy:boolean;start:(kind:'discover'|'plan'|'adjust',b:Brief)=>Promise<void>;cancel:()=>Promise<void>;resume:(s:string)=>Promise<void>;apply:()=>Promise<void>}){
 const [answer,setAnswer]=useState(''),[selected,setSelected]=useState<Candidate|null>(null);const setBrief=useSession(s=>s.setBrief)
 if(!run)return <div className="screen"><Header title="旅行规划"/><div className="empty-state"><Compass size={30}/><h2>从一个想法开始</h2><p>填写旅行条件，让 AI 查询资料并提出计划。</p><button className="primary-button" onClick={()=>go('brief')}>开始规划</button></div></div>
 if(['queued','running'].includes(run.status))return <div className="screen"><Header title="正在为你规划" back="brief"/><div className="planning"><div className="planning-orbit"><Compass size={34}/></div><h2>让想法，慢慢成形</h2><p>正在查找适合你的地点与路线。</p><div className="progress-stage" aria-live="polite"><LoaderCircle className="spin" size={17}/>{run.stage||'等待开始'}</div><ul><li><Check size={14}/>你的条件已保存</li><li><LoaderCircle className="spin" size={14}/>查询资料与安排旅程</li><li>○ 完成后由你确认</li></ul><button className="secondary-button" onClick={()=>void cancel()}>取消本次规划</button><small>可以先离开此页，回来后继续查看进度。</small></div></div>
 if(run.status==='needs_input')return <div className="screen"><Header title="再了解一点" back="brief"/><section className="clarify"><Sparkles size={26}/><h2>这会让计划更适合你</h2><p>{run.question}</p><textarea aria-label="补充旅行需求" value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={2000}/><button className="primary-button" disabled={!answer.trim()||busy} onClick={()=>void resume(answer)}>补充并继续<ArrowRight size={17}/></button></section></div>
 if(['failed','cancelled','committed'].includes(run.status))return <div className="screen"><Header title="规划状态" back="brief"/><div className="empty-state"><h2>{run.status==='failed'?'这次规划没能完成':run.status==='cancelled'?'本次规划已取消':'行程已保存'}</h2><p>{run.error||'你可以返回修改条件，重新开始。已有行程仍然保留。'}</p><button className="primary-button" onClick={()=>go('brief')}>返回旅行条件</button></div></div>
 if(run.proposal?.kind==='destinations'){const candidates=run.proposal.candidates;return <div className="screen"><Header title="适合你的几个方向" back="brief"/><div className="page-intro"><p className="eyebrow">FIND YOUR NEXT PLACE</p><h2>先比较，再决定</h2><p>{run.brief.days} 天 · {run.brief.origin||'出发地未填'} · {run.brief.pace}节奏</p></div><div className="candidate-stack">{candidates.map((c,i)=><article className={'candidate-card '+(selected?.id===c.id?'selected':'')} key={c.id}><div className="candidate-top"><span>方向 {String(i+1).padStart(2,'0')}</span><button className="icon-button" aria-label={'比较'+c.name} onClick={()=>setSelected(selected?.id===c.id?null:c)}><SlidersHorizontal size={18}/></button></div><h3>{c.name}</h3><p>{c.reason}</p><div className="tradeoff"><b>需要考虑</b>{c.tradeoff}</div><a href={c.sourceUrl} target="_blank" rel="noreferrer">地点资料来源<ExternalLink size={13}/></a><button className="primary-button" disabled={busy} onClick={()=>{const next={...run.brief,destination:c.name};setBrief(next);void start('plan',next)}}>选择这里，规划行程<ArrowRight size={16}/></button></article>)}</div>{selected&&<div className="comparison"><h3>比较目的地</h3><p>以相同的预算、交通与节奏条件看取舍。</p>{candidates.map(c=><div key={c.id}><b>{c.name}</b><p>{c.reason}</p><small>{c.tradeoff}</small></div>)}</div>}</div>}
 if(run.proposal?.kind==='itinerary'){const plan=run.proposal.plan;return <div className="screen"><Header title={run.kind==='adjust'?'确认这次调整':'你的行程草案'} back={run.kind==='adjust'?'trip':'brief'}/><section className="review-intro"><Pill/><h2>{plan.destination} · {plan.days.length} 天</h2><p>{plan.summary}</p></section>{run.kind==='adjust'&&<section className="diff-card"><h3>这次改了什么</h3>{run.diff?.map((d,i)=><p key={i}><Check size={14}/>{d}</p>)}</section>}<Warnings warnings={plan.warnings}/>{plan.days.map(d=><div className="review-day" key={d.day}><h3>DAY {d.day} <span>{d.title}</span></h3>{d.stops.map(s=><div key={s.placeId}><time>{s.startTime}</time><b>{run.places?.find(p=>p.id===s.placeId)?.name||s.placeId}</b><small>{s.durationMinutes} 分钟 · 建议停留</small></div>)}</div>)}<button className="primary-button" disabled={busy} onClick={()=>void apply()}><Check size={18}/>{busy?'正在保存':'确认并保存这份行程'}</button><p className="footnote">确认后才会写入行程；版本冲突时会提示重新规划。</p></div>}
 return <div className="screen"><Header title="规划状态"/><p>正在恢复结果……</p></div>
}
function Warnings({warnings}:{warnings:string[]}){const [expanded,setExpanded]=useState(false);if(!warnings.length)return null;return <section className="warnings"><button onClick={()=>setExpanded(!expanded)}><ShieldCheck size={16}/><span>{warnings.length} 项信息需要留意</span>{expanded?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>{expanded&&<ul>{warnings.map((w,i)=><li key={i}>{w}</li>)}</ul>}</section>}
function TripPage({trip,health,busy,save,detail,adjust,undo}:{trip:Itinerary|null;health:Health|null;busy:boolean;save:(plan:Plan,ids?:string[])=>Promise<void>;detail:(p:Fact)=>void;adjust:(s:string,days:number[])=>Promise<void>;undo:()=>Promise<void>}){
 const setActiveDay=useSession(s=>s.setActiveDay)
 const [dayIndex,setDayIndex]=useState(()=>trip?useSession.getState().activeDays[trip.id]||0:0),[view,setView]=useState<'list'|'map'>('list'),[request,setRequest]=useState(''),[allDays,setAllDays]=useState(false),[backup,setBackup]=useState(false),[moveId,setMoveId]=useState(''),[localUndo,setLocalUndo]=useState<Plan|null>(null),[selectedMoveDay,setSelectedMoveDay]=useState(1)
 const day=trip?.plan.days[Math.min(dayIndex,(trip?.plan.days.length||1)-1)];const facts=useMemo(()=>day?.stops.map(s=>trip?.places.find(p=>p.id===s.placeId)).filter((p):p is Fact=>Boolean(p))||[],[trip,day]);
 if(!trip||!day)return <div className="screen"><Header title="我的行程"/><div className="empty-state"><Map size={30}/><h2>下一段旅程，从这里开始</h2><p>先选目的地，再安排每一天。</p><button className="primary-button" onClick={()=>go('home')}>去探索</button></div></div>
 const edit=(plan:Plan)=>{setLocalUndo(trip.plan);void save(plan)}
 const remove=(id:string)=>edit({...trip.plan,days:trip.plan.days.map(d=>({...d,stops:d.stops.filter(s=>s.placeId!==id)}))})
 const reorder=(index:number,direction:number)=>{const stops=[...day.stops],other=index+direction;if(other<0||other>=stops.length)return;const a=stops[index],b=stops[other];if(trip.lockedIds.includes(a.placeId)||trip.lockedIds.includes(b.placeId))return;stops[index]={...b,startTime:a.startTime};stops[other]={...a,startTime:b.startTime};edit({...trip.plan,days:trip.plan.days.map(d=>d.day===day.day?{...d,stops}:d)})}
 const used=trip.plan.days.flatMap(d=>d.stops.map(s=>s.placeId));const backups=trip.places.filter(p=>!used.includes(p.id));
 return <div className="screen trip-screen"><Header title="我的旅程" back="saved"><button className="icon-button" aria-label="导出行程" onClick={()=>downloadTrip(trip)}><Download size={18}/></button></Header><section className="trip-cover"><img src={photos[2]} alt="旅行氛围图"/><div className="hero-shade"/><div><p className="eyebrow">YOUR NEXT CHAPTER</p><h2>{trip.plan.destination}</h2><p>{trip.brief.days} 天 · {trip.brief.pace}节奏</p></div><span className="photo-caption">旅行氛围图</span></section><section className="trip-title"><Pill example={trip.dataMode==='example'}/><h1>{trip.plan.destination}<span>{trip.brief.days} 天的自在旅程</span></h1><p>{trip.plan.summary}</p><div className="trip-meta"><span>{trip.brief.startDate||'日期待定'}</span><i>·</i><span>{trip.brief.pace}节奏</span><i>·</i><span>版本 {trip.revision}</span></div></section>
 <div className="day-selector" aria-label="选择行程日期">{trip.plan.days.map((d,i)=><button key={d.day} className={dayIndex===i?'active':''} onClick={()=>{setDayIndex(i);setActiveDay(trip.id,i)}}><small>DAY</small><b>{d.day}</b></button>)}</div><div className="day-heading"><div><small>DAY {day.day}</small><h2>{day.title}</h2></div><div className="view-toggle"><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="列表视图"><SlidersHorizontal size={17}/></button><button className={view==='map'?'active':''} onClick={()=>setView('map')} aria-label="地图视图"><Map size={17}/></button></div></div>
 {view==='map'&&<Suspense fallback={<div className="empty-inline">正在加载地图……</div>}><TripMap items={facts} example={trip.dataMode==='example'}/></Suspense>}
 <div className="timeline">{day.stops.map((s,i)=>{const p=trip.places.find(p=>p.id===s.placeId);if(!p)return null;const locked=trip.lockedIds.includes(p.id);return <article className="stop" key={p.id}><div className="timeline-rail"><time>{s.startTime}</time><span>{i+1}</span></div><div className="stop-content"><div className="stop-top"><small><MapPin size={11}/>{p.category.split(';')[0]}</small><button className={'icon-button '+(locked?'locked':'')} aria-label={(locked?'解锁':'锁定')+p.name} onClick={()=>void save(trip.plan,locked?trip.lockedIds.filter(id=>id!==p.id):[...trip.lockedIds,p.id])}>{locked?<LockKeyhole size={15}/>:<UnlockKeyhole size={15}/>}</button></div><button className="place-title" onClick={()=>detail(p)}>{p.name}<ExternalLink size={13}/></button><p>{s.note}</p><span className="duration">建议停留 {s.durationMinutes} 分钟</span><div className="stop-bottom"><span>{p.openingHours||'开放时间待核实'}</span><div><button disabled={locked||i===0} aria-label={'上移'+p.name} onClick={()=>reorder(i,-1)}><ChevronUp size={16}/></button><button disabled={locked||i===day.stops.length-1} aria-label={'下移'+p.name} onClick={()=>reorder(i,1)}><ChevronDown size={16}/></button><button disabled={locked} aria-label={'跨天移动'+p.name} onClick={()=>{setMoveId(p.id);setSelectedMoveDay(day.day)}}><ArrowRight size={16}/></button><button disabled={locked} aria-label={'删除'+p.name} onClick={()=>remove(p.id)}><Trash2 size={15}/></button></div></div></div></article>})}</div>
 {!day.stops.length&&<div className="empty-inline">留白的一天。添加一个地点，或让 AI 帮你安排。</div>}<button className="add-place" onClick={()=>setBackup(true)}><Plus size={17}/>添加备选地点</button><div className="trip-tools"><button disabled={busy} onClick={()=>trip.dataMode==='example'&&localUndo?edit(localUndo):void undo()}><RotateCcw size={14}/>撤销上一次修改</button><span><Check size={13}/>{trip.dataMode==='example'?'保存在此浏览器':'已保存到服务端'}</span></div><Warnings warnings={trip.plan.warnings}/>
 <section className="ai-adjust"><div><Sparkles size={18}/><b>想改哪里，直接说</b></div><p>已锁定的安排会保留。AI 先提出修改，由你确认。</p><label className="scope-choice"><input type="checkbox" checked={allDays} onChange={e=>setAllDays(e.target.checked)}/>{allDays?'允许调整整个行程':`只调整第 ${day.day} 天`}</label><textarea aria-label="调整行程的要求" value={request} onChange={e=>setRequest(e.target.value)} placeholder="第二天下午少走一点，保留博物馆……" maxLength={2000}/><button className="primary-button" disabled={!request.trim()||busy||!health?.ready||trip.dataMode==='example'} onClick={()=>void adjust(request,allDays?trip.plan.days.map(d=>d.day):[day.day])}>生成调整建议<ArrowRight size={17}/></button>{trip.dataMode==='example'&&<small>示例行程支持手动编辑；真实 AI 调整需先查询生成正式行程。</small>}</section>
 {backup&&<Modal title="添加到这一天" close={()=>setBackup(false)}><p className="muted">仅显示已查询或已收录的备选地点。</p>{!backups.length?<p>当前没有备选地点。真实行程可以让 AI 查询并建议新增地点。</p>:backups.map(p=><button className="backup-item" key={p.id} onClick={()=>{const last=day.stops.at(-1);let minutes=last?Number(last.startTime.slice(0,2))*60+Number(last.startTime.slice(3))+last.durationMinutes+60:540;minutes=Math.min(minutes,1320);edit({...trip.plan,days:trip.plan.days.map(d=>d.day===day.day?{...d,stops:[...d.stops,{placeId:p.id,startTime:`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`,durationMinutes:60,note:'手动添加，时间为建议，请核实交通和开放情况。'}]}:d)});setBackup(false)}}><span><b>{p.name}</b><small>{p.category.split(';')[0]}</small></span><Plus size={18}/></button>)}</Modal>}
 {moveId&&<Modal title="移动到另一天" close={()=>setMoveId('')}><label className="field"><span>选择日期</span><select value={selectedMoveDay} onChange={e=>setSelectedMoveDay(Number(e.target.value))}>{trip.plan.days.map(d=><option key={d.day} value={d.day}>第 {d.day} 天 · {d.title}</option>)}</select></label><p className="muted">目标日期的时间和交通需要重新核实。</p><button className="primary-button" disabled={selectedMoveDay===day.day} onClick={()=>{const stop=day.stops.find(s=>s.placeId===moveId)!;const target=trip.plan.days.find(d=>d.day===selectedMoveDay)!;const last=target.stops.at(-1);const minutes=last?Number(last.startTime.slice(0,2))*60+Number(last.startTime.slice(3))+last.durationMinutes+60:540;if(minutes+stop.durationMinutes>1440)return;edit({...trip.plan,days:trip.plan.days.map(d=>d.day===selectedMoveDay?{...d,stops:[...d.stops,{...stop,startTime:`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`}]}:{...d,stops:d.stops.filter(s=>s.placeId!==moveId)})});setMoveId('')}}>确认移动</button></Modal>}
 </div>
}
function downloadTrip(trip:Itinerary){const blob=new Blob([JSON.stringify(trip,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=trip.plan.destination+'-行程.json';a.click();URL.revokeObjectURL(url)}
function SavedPage(){const {trips,select}=useSession();return <div className="screen"><Header title="我的行程"/><div className="page-intro"><p className="eyebrow">YOUR JOURNEYS</p><h2>想去的地方，留在这里</h2><p>每段旅程独立保存，重新规划不会替换其他行程。</p></div>{!trips.length?<div className="empty-state"><Map size={30}/><h3>还没有保存的行程</h3><button className="primary-button" onClick={()=>go('home')}>开始探索</button></div>:trips.map(t=><button className="saved-card" key={t.id} onClick={()=>{select(t.id);go('trip')}}><div className="saved-art"><Compass size={30}/></div><div><Pill example={t.dataMode==='example'}/><h3>{t.plan.destination} · {t.brief.days} 天</h3><small>{new Date(t.updatedAt).toLocaleDateString('zh-CN')} · 版本 {t.revision}</small></div><ArrowRight size={18}/></button>)}</div>}
function SettingsPage({health,refresh,onError,cleared}:{health:Health|null;refresh:()=>Promise<void>;onError:(s:string)=>void;cleared:()=>void}){
 const [confirm,setConfirm]=useState(false);return <div className="screen"><Header title="设置"/><div className="page-intro"><p className="eyebrow">READY WHEN YOU ARE</p><h2>连接你的规划服务</h2><p>配置完成后即可启用真实查询。密钥仅保存在服务端。</p></div><div className="service-card"><h3>服务状态</h3>{[{name:'AI 模型',ok:health?.modelConfigured},{name:'地点与路线',ok:health?.placesConfigured},{name:'网页检索（可选）',ok:health?.searchConfigured}].map(s=><div key={s.name}><span>{s.name}</span><b className={s.ok?'connected':''}>{s.ok?'已配置':'待配置'}</b></div>)}<small>{health?.coverage||'等待服务响应'}</small><button className="secondary-button" onClick={()=>void refresh().catch(e=>onError(e.message))}>重新检查</button></div>
 <details className="setup-details"><summary>开发配置说明</summary><p>在项目根目录将 .env.example 复制为 .env，填写：</p><code>MODEL_API_KEY<br/>MODEL_NAME<br/>MODEL_BASE_URL<br/>MODEL_PROTOCOL<br/>AMAP_WEB_KEY</code><p>可选：TAVILY_API_KEY（网页检索）。重启服务后再检查连接状态。</p><p>“已配置”仅表示参数存在，首次真实调用仍需验证账号权限与额度。</p></details><div className="service-card"><h3>数据与隐私</h3><p>旅行条件、行程与规划进度用于本次服务。匿名会话只可读取自己的计划；清除后将无法恢复。</p><button className="delete-button" onClick={()=>setConfirm(true)}><Trash2 size={16}/>清除我的旅行记录</button></div>{confirm&&<Modal title="清除所有旅行记录？" close={()=>setConfirm(false)}><p>将删除当前匿名会话的服务端行程、提案和本地 v0.3 记录。其他用户的数据不会受影响。此操作无法撤销。</p><button className="danger-button" onClick={async()=>{try{await api('/session',{},'DELETE');useSession.getState().clear();cleared();setConfirm(false);go('home')}catch(e){onError((e as Error).message)}}}>确认清除</button></Modal>}</div>
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close()},[])
 return <dialog ref={ref} className="modal" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-header"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="关闭"><X size={20}/></button></div>{children}</dialog>
}
export default App
