import {create} from 'zustand'
import {BriefSchema,TripSchema} from '../shared/schema'
import type {Brief,Itinerary} from './domain'
import {emptyBrief} from './domain'
type State={brief:Brief;trips:Itinerary[];selectedId:string|null;runId:string|null;saveError:string|null;activeDays:Record<string,number>;setActiveDay:(id:string,day:number)=>void;setBrief:(b:Brief)=>void;saveTrip:(t:Itinerary)=>void;select:(id:string)=>void;setRun:(id:string|null)=>void;mergeTrips:(t:Itinerary[])=>void;clear:()=>void;retry:()=>void}
const key='travel-product-v3';let saved:{brief?:Brief;trips?:Itinerary[];selectedId?:string;runId?:string;activeDays?:Record<string,number>}={};let initialError:string|null=null;let corruptRaw:string|null=null
try{const raw=localStorage.getItem(key);if(raw){const value=JSON.parse(raw);if(value.schemaVersion!==3)throw Error('version');saved={brief:BriefSchema.parse(value.brief),trips:value.trips.map((t:Itinerary)=>TripSchema.parse(t.dataMode==='example'?{...t,places:t.places.map(p=>p.coordinate[1]>90?{...p,coordinate:[p.coordinate[1],p.coordinate[0]]}:p)}:t)),selectedId:value.selectedId,runId:value.runId,activeDays:Object.fromEntries(Object.entries(value.activeDays||{}).filter(([,day])=>typeof day==='number'&&Number.isInteger(day)&&day>=0&&day<14)) as Record<string,number>}}}catch{try{corruptRaw=localStorage.getItem(key)}catch{corruptRaw=null}initialError='本地记录无法读取。旧记录已保留，可以重新规划；新计划保存后会替换此版本记录。'}
export const useSession=create<State>((set,get)=>{
 const persist=()=>{const s=get();try{if(corruptRaw){localStorage.setItem(key+'-recovery-'+Date.now(),corruptRaw);corruptRaw=null}localStorage.setItem(key,JSON.stringify({schemaVersion:3,brief:s.brief,trips:s.trips,selectedId:s.selectedId,runId:s.runId,activeDays:s.activeDays}));set({saveError:null})}catch{set({saveError:'浏览器保存失败，本次记录只保留在当前页面。请导出备份或重试保存。'})}}
 return {brief:saved.brief||emptyBrief,trips:saved.trips||[],selectedId:saved.selectedId||null,runId:saved.runId||null,saveError:initialError,activeDays:saved.activeDays||{},setActiveDay:(id,day)=>{set({activeDays:{...get().activeDays,[id]:day}});persist()},
  setBrief:brief=>{set({brief});persist()},saveTrip:trip=>{const checked=TripSchema.safeParse(trip);if(!checked.success){set({saveError:'行程资料格式无效，原记录已保留。'});return}set({trips:[trip,...get().trips.filter(t=>t.id!==trip.id)],selectedId:trip.id});persist()},select:id=>{set({selectedId:id});persist()},setRun:runId=>{set({runId});persist()},mergeTrips:trips=>{const examples=get().trips.filter(t=>t.dataMode==='example');set({trips:[...trips,...examples]});persist()},clear:()=>{set({brief:emptyBrief,trips:[],selectedId:null,runId:null,activeDays:{}});persist()},retry:persist}
})
